% =========================================================================
% heb_perm_fig.m
% =========================================================================
% Figure script for permutation-based assessment of structure-based priors
% (Fig. S5 visualization)
%
% Context:
% This script visualizes network-wise outputs from permutation BMR + RFX
% BMC (generated by the full 17-network analysis). It summarizes, for each
% network, first-level evidence gains under:
%   k = 1   : informed second-level prior (structure-based)
%   k = 2:K : permuted second-level priors (nonsense models; K = 100)
%
% Loaded quantities:
% From each <Network>_bmc_results.mat file:
%   - perm_1st_logBFs(s,k), where:
%       perm_1st_logBFs(s,k) = ln BF^(1)_{s,uninformed,k}
%   - Ef(k): expected model frequencies from RFX BMC
%   - ep(k): exceedance probabilities from RFX BMC
%
% What is shown:
% Panel A (17 subplots):
%   - Bars = Ef over K models for each network.
%   - Red bar = informed model (k = 1).
%   - Gray bars = permuted models (k = 2:K).
%   - Text annotation reports phi_1 = ep(1), the exceedance probability of
%     the informed model.
%
% Panel B (single scatter):
%   - y-axis = proportion of subjects with perm_1st_logBFs(:,1) > 0
%              (informed prior).
%   - x-axis = mean over k = 2:K of the proportion of subjects with
%              perm_1st_logBFs(:,k) > 0 (permuted priors).
%   - Dashed line: equality (x = y).
%   - Dotted lines: reference threshold at 0.8 on each axis.
%
% Inputs:
% Expects files in ./mfreqs named <Network>_bmc_results.mat containing:
% perm_1st_logBFs, Ef, ep.
%
% =========================================================================
% Paths
% =========================================================================
mfreqs_path = fullfile(pwd, 'mfreqs');
if ~exist(mfreqs_path, 'dir')
    error('Result directory not found: %s', mfreqs_path);
end

% Networks
net_stub    = {'ContA', 'ContB', 'ContC', 'DefaultA', 'DefaultB', ...
            'DefaultC', 'DorsAttnA', 'DorsAttnB', 'LimbicA', 'LimbicB', ...
            'SalVentAttnA', 'SalVentAttnB', 'SomMotA', 'SomMotB', ...
            'TempPar', 'VisCent', 'VisPeri'};
net_format  = {'Control A', 'Control B', 'Control C', 'Default A',...
            'Default B', 'Default C', 'Attention A', 'Attention B', ...
            'Limbic A', 'Limbic B', 'Salience A', 'Salience B', ...
            'SomMot A', 'SomMot B', 'TempPar', 'Visual Cent', ...
            'Visual Peri'};

% Variables for storing/plotting relevant expected frequencies
n_nets          = numel(net_stub);  % Number of networks 
inf_Ef          = nan(n_nets,1);    % Expected freqs for informed
prop_inf        = nan(n_nets,1);    % Proportion F>0 for informed prior
prop_perm_mean  = nan(n_nets,1);    % Mean proportion F>0 across perms
ax              = cell(n_nets+1,1); % Figure axes

% Colours
red  = [0.8 0.1 0.1];
grey = 0.75*[1 1 1];
hasNetworkColour = exist('network_colour', 'file') == 2;
fallbackCmap = lines(n_nets);

% Visualise the expected model frequencies (with the structurally informed
% prior [red] and nonsense priors [gray]). We report the exceedance 
% probability for the informed model too (in the top right of the plots).
figure;
set(gcf, 'Units', 'normalized', 'Position', [0.03 0.06 0.94 0.88]);
for m = 1:n_nets
    load(fullfile(mfreqs_path, [net_stub{m},'_bmc_results.mat']), ...
        "perm_1st_logBFs", "Ef", "ep");

    % Store expected frequencies
    inf_Ef(m)       = Ef(1);
    % Figure panel
    ax{m}           = subplot(3, 6, m);

    % Build bars
    n_models        = numel(Ef);
    barCols         = repmat(grey, n_models, 1);
    barCols(1,:)    = red;

    % Plot bars
    b       = bar(1:n_models, Ef, 'FaceColor', 'flat', ...
        'EdgeColor', 'none');
    b.CData = barCols;

    % Axis formatting
    title(net_format{m}, 'Interpreter', 'none', 'FontSize', 14,...
        'FontWeight', 'normal');
    ylim([0 1]);
    xlim([-3 n_models+3]);
    box off;
    set(gca, 'XTick', [1, n_models]);
    if 1-Ef(1) <= .08
        set(gca, 'YTick', [0, Ef(1)]);
    else
        set(gca, 'YTick', [0, Ef(1), 1]);
    end
    yticklabels(arrayfun(@(x) sprintf('%.2f', x),...
        [0, Ef(1), 1], 'UniformOutput', false));
    set(gca, 'FontSize', 18);

    % Exceedance probability for informed model
    ep_SC = ep(1);  
    txt   = sprintf('\\phi_{1} = %.2f', ep_SC);
    text(0.98, 0.98, txt, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'top', ...
        'Interpreter', 'tex', ...
        'FontSize', 18);


    % Print and store the informed vs permuted BFs > 0
    x                 = perm_1st_logBFs > 0;
    p_inf             = sum(x(:,1)) / length(x(:,1));
    p_perm_vec        = sum(x(:,2:end)) ./ length(x(:,1));
    p_perm_mu         = mean(p_perm_vec);
    prop_inf(m)       = p_inf;
    prop_perm_mean(m) = p_perm_mu;

    fprintf('\n=====================================================\n');
    fprintf('Proportion of non-negative log-BFs for: %s\n', net_format{m});
    fprintf('Informed = %.2f\n', p_inf);
    fprintf('Permuted; Mean = %.2f ± %.3f\n',...
        p_perm_mu, std(p_perm_vec));
    fprintf('\n=====================================================\n');
end

% -------------------------------------------------------------------------
% Final panel: parity plot vis-a-vis proportion F>0 (SC vs permuted)
% -------------------------------------------------------------------------
ax{n_nets+1} = subplot(3, 6, 18);
hold on;

% Limits
lims = [0, 1];
plot(lims, lims, 'k--', 'LineWidth', 1);
xline(0.8, ':k', 'LineWidth', 1);
yline(0.8, ':k', 'LineWidth', 1);
xticks([0, 1/2, 0.8, 1]);
yticks([0, 1/2, 0.8, 1]);

for m = 1:n_nets
    if hasNetworkColour
        thisColor = network_colour(m);
    else
        thisColor = fallbackCmap(m, :);
    end
    scatter(prop_perm_mean(m), prop_inf(m), 60, ...
        'MarkerFaceColor', thisColor, ...
        'MarkerEdgeColor', 'none');
end

xlim(lims);
ylim(lims);
axis square;
box off;
set(gca, 'FontSize', 18);
xlabel(['Mean proportion of positive', newline, ...
    'log-BFs (permuted priors)'], 'FontSize', 18);
ylabel(['Proportion of positive', newline, ...
    'log-BFs (informed prior)'], 'FontSize', 18);

% Label for panel(s) A (first subplots)
annotation('textbox', [0.13, 0.94, 0.05, 0.05], ...
    'String', '\bf A', ...
    'FontSize', 20, ...
    'LineStyle', 'none', ...
    'Interpreter', 'tex');

% Label for panel B (final subplot)
posB = get(ax{n_nets+1}, 'Position');

% Convert subplot position to figure annotation coordinates
% Use a small offset above the subplot
annotation('textbox', [posB(1)-0.02, posB(2)+posB(4), 0.05, 0.05], ...
    'String', '\bf B', ...
    'FontSize', 20, ...
    'LineStyle', 'none', ...
    'Interpreter', 'tex');

% Global X label
annotation('textbox', [0.12 0.02 0.60 0.04], ...
    'String', 'Models', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 20, ...
    'LineStyle', 'none');

% Global Y label 
annotation('textbox', [0.275 0.25 0.3 0.8], ...
    'String', 'Expected frequencies', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 20, ...
    'Rotation', 90, ...
    'LineStyle', 'none');
