% =========================================================================
% heb_perm_bmr_rfx_bmc_toy.m
% =========================================================================
% Toy demonstration of permutation-based BMR + RFX BMC for structure-based
% priors (Control A network only)
%
% Context:
% This script is a lightweight, demonstration of the permutation analysis 
% described in the associated paper's supporting information (SI) section:
% "Permutation-based assessment of structure-based priors".
%
% The full pipeline runs the same logic across 17 networks and larger data 
% structures. Here we intentionally run only one network (ContA; Control A)
% so the procedure can be shared and executed without shipping very large 
% DCM/HEB files.
%
% Question addressed:
% Do first-level evidence gains induced by a structure-based second-level
% prior reflect specific structural information, or could similar gains
% arise generically from shrinkage?
%
% Following the SI analysis, we compare first-level evidence gains under:
%   k = 1   : an informed second-level prior (structure-based)
%   k = 2:K : nonsense priors built via permutation (K = 100 here)
%
% -------------------------------------------------------------------------
% Procedure implemented in this script
% -------------------------------------------------------------------------
% 1) Load toy HEB outputs for ContA:
%      iFs  = subject free energies under uninformed prior
%      viFs = subject free energies under informed prior
%      vPEB = informed group-level model
%      unPEB = uninformed group-level model
%
% 2) Construct the competing model set.
%    - Model 1 is the model inverted under the structurally informed prior 
%      covariance matrix.
%    - Models 2..K are generated by permuting inter-regional prior
%      variances from the strict lower triangle of the variance map,
%      then symmetrizing so paired effects (a_ij and a_ji) have equal
%      prior variance.
%
% 3) For each permuted prior, perform group-level BMR via
%    spm_log_evidence_reduce(Ep, Cp, pE, pC, pE, rC) to obtain reduced
%    group posteriors (sE, sC).
%
% 4) Propagate reduced group posteriors to first level:
%    for each subject DCM, run spm_log_evidence_reduce on A-parameter
%    posteriors to obtain reduced first-level evidence for that model.
%
% 5) Build subject-level log Bayes factors relative to uninformed models:
%      ln BF^(1)_{s,uninformed,k} = F^(1)_{s,k} - F^(1)_{s,uninformed}
%    stored in perm_1st_logBFs (subjects x models). The Gaussian complexity
%    correction Fc is distributed as Fc/n.
%
% 6) Run random-effects Bayesian model comparison across K models using
%    VBA_groupBMC to estimate expected model frequencies (Ef) and
%    exceedance probabilities (ep).
%
% 7) Save outputs for plotting/reporting (e.g., Fig. S6-style summaries).
%
% What this helps show
% --------------------
% This procedure tests whether first-level evidence gains are specific to
% the informed second-level prior. If model 1 consistently has higher Ef
% and ep, and more subjects with positive ln BF^(1)_{s,uninformed,1}, than
% the permuted models, this supports structure-specific information 
% transfer from second-level priors to first-level evidence. If permuted 
% models perform similarly, the gains are more consistent with nonspecific
% regularization/shrinkage.
%
% Inputs expected in ./models
% ---------------------------
%   - re-test_heb/*ContA*       : iFs, viFs, vPEB, unPEB
%   - re-test_dcms/**/*DCM_ContA*: subject-level DCMs
%
% Outputs written to ./models/mfreqs_toy
% --------------------------------------
%   - ContA_bmc_results.mat containing:
%       perm_1st_logBFs, perm_2nd_logBFs, Ef, ep, postRFX, outRFX,
%       win_counts, F_group, net, itt
%
% Dependencies
% ------------
% SPM12 and VBA-toolbox must already be on the MATLAB path.
%
% =========================================================================
% Dependency checks
% =========================================================================
requiredFns = {'spm_log_evidence_reduce', 'spm_fieldindices', ...
               'spm_vec', 'spm_inv', 'spm_logdet', 'VBA_groupBMC'};
missingFns = requiredFns(cellfun(@(f) isempty(which(f)), requiredFns));
if ~isempty(missingFns)
    missingList = strjoin(missingFns, [newline, '  - ']);
    error(['Missing required toolbox function(s):\n  - %s\n', ...
        'Add SPM12 and VBA-toolbox to the MATLAB path, then rerun.'], ...
        missingList);
end

% =========================================================================
% Paths and configuration
% =========================================================================
mdl_path = fullfile(pwd, 'models');
heb_path = fullfile(mdl_path, 're-test_heb');
dcm_path = fullfile(mdl_path, 're-test_dcms');
mfs_path = fullfile(mdl_path, 'mfreqs_toy');

if ~exist(heb_path, 'dir')
    error('HEB directory not found: %s', heb_path);
end
if ~exist(dcm_path, 'dir')
    error('DCM directory not found: %s', dcm_path);
end
if ~exist(mfs_path, 'dir')
    mkdir(mfs_path);
end

networks = {'ContA'};
itt = 100;           % Total competing models (1 informed + 99 permuted)
jitter = 1/64;       % Small diagonal stabilizer for permuted variance map
M = numel(networks);

% =========================================================================
% Network loop (toy dataset uses Control A only)
% =========================================================================
for m = 1:M
    net = networks{m};
    fprintf('\n-----------------------------------------------------\n');
    fprintf('Network %d/%d: %s\n', m, M, net);
    fprintf('-----------------------------------------------------\n');

    % ---------------------------------------------------------------------
    % Load HEB/PEB quantities for this network
    % ---------------------------------------------------------------------
    heb = dir(fullfile(heb_path, ['*', net, '*']));
    if isempty(heb)
        warning('No HEB file found for %s in %s. Skipping.', net, ...
            heb_path);
        continue;
    end
    [~, hebOrder] = sort({heb.name});
    heb = heb(hebOrder);
    if numel(heb) > 1
        warning('Multiple HEB files found for %s; using %s.', net, ...
            heb(1).name);
    end

    hebFile = fullfile(heb(1).folder, heb(1).name);
    hebData = load(hebFile, 'iFs', 'viFs', 'vPEB', 'unPEB');
    iFs = hebData.iFs;
    viFs = hebData.viFs;
    vHEB = hebData.vPEB;
    unHEB = hebData.unPEB;

    % Group-level priors/posteriors
    pE = vHEB.M.pE;
    pC = vHEB.M.pC;
    Ep = vHEB.Ep;
    Cp = vHEB.Cp;

    % ---------------------------------------------------------------------
    % Precompute permutation indices over prior variances
    % ---------------------------------------------------------------------
    Np = sqrt(length(pC));
    if mod(Np, 1) ~= 0
        error('pC length (%d) is not a perfect square for %s.', ...
            length(pC), net);
    end
    Np = round(Np);
    vars = reshape(diag(pC), Np, Np);
    idxLower = find(tril(vars, -1));
    values = vars(idxLower);

    % ---------------------------------------------------------------------
    % Load subject-level DCMs
    % ---------------------------------------------------------------------
    files = dir(fullfile(dcm_path, '**', ['*DCM_', net, '*']));
    if isempty(files)
        warning('No DCM files found for %s in %s. Skipping.', net, ...
            dcm_path);
        continue;
    end
    fileKeys = fullfile({files.folder}, {files.name});
    [~, fileOrder] = sort(fileKeys);
    files = files(fileOrder);

    n = numel(files);
    GCM = cell(n, 1);
    for j = 1:n
        dcmData = load(fullfile(files(j).folder, files(j).name), 'DCM');
        GCM{j} = dcmData.DCM;
    end

    if numel(iFs) ~= n || numel(viFs) ~= n
        warning(['Mismatch between HEB vector lengths and DCM count', ...
            ' for %s: numel(iFs)=%d, numel(viFs)=%d, nDCM=%d.'], ...
            net, numel(iFs), numel(viFs), n);
    end

    % Identify A-parameter block once (all subjects share template)
    indx = spm_fieldindices(GCM{1}.M.pE, 'A');

    DEp_all = cell(n, 1);
    DCp_all = cell(n, 1);
    for j = 1:n
        DEp_all{j} = GCM{j}.Ep.A;
        DCp = GCM{j}.Cp;
        DCp_all{j} = full(DCp(indx, indx));
    end

    % Complexity term is constant across permutations
    Fc = Fc_gaussKL(Ep, Cp, pE, pC);

    % ---------------------------------------------------------------------
    % Containers: model 1 is the informed prior
    % ---------------------------------------------------------------------
    perm_1st_logBFs = nan(n, itt);
    perm_2nd_logBFs = nan(1, itt);
    perm_1st_logBFs(:, 1) = viFs(:) - iFs(:);
    perm_2nd_logBFs(1, 1) = vHEB.F - unHEB.F;

    % ---------------------------------------------------------------------
    % Permutation loop for nonsense priors (models 2..itt)
    % ---------------------------------------------------------------------
    for ii = 2:itt
        rng(ii * 17, 'twister');  % deterministic per permutation index

        valuesPerm = values(randperm(numel(values)));
        rC_perm = zeros(Np);
        rC_perm(idxLower) = valuesPerm;
        rC_perm = rC_perm + rC_perm' + jitter * eye(Np);
        rC = diag(rC_perm(:));

        % Group-level reduction under permuted prior
        [~, sE, sC] = spm_log_evidence_reduce(Ep, Cp, pE, pC, pE, rC);

        % First-level reductions for each subject
        pFs = nan(n, 1);
        fprintf('Iteration %d: reducing models', ii - 1);
        for j = 1:n
            fprintf('.');
            [pFs(j), ~, ~] = spm_log_evidence_reduce(DEp_all{j}, ...
                DCp_all{j}, pE, pC, sE, sC);
        end
        fprintf('\n');

        perm_1st_logBFs(:, ii) = pFs - iFs(:) - Fc / n;
        perm_2nd_logBFs(1, ii) = sum(perm_1st_logBFs(:, ii)) - unHEB.F;
    end

    % ---------------------------------------------------------------------
    % Random-effects BMC across informed + permuted models
    % ---------------------------------------------------------------------
    [~, winModel] = max(perm_1st_logBFs, [], 2);
    win_counts = accumarray(winModel, 1, [itt 1]);
    F_group = sum(perm_1st_logBFs, 1);

    optionsBMC = struct;
    optionsBMC.DisplayWin = 0;
    optionsBMC.verbose = 1;
    optionsBMC.families = [];
    optionsBMC.figName = sprintf('Permutation BMC: %s', net);

    modelNames = cell(1, itt);
    modelNames{1} = 'Informed';
    for ii = 2:itt
        modelNames{ii} = sprintf('Nonsense_%03d', ii - 1);
    end
    optionsBMC.modelNames = modelNames;

    [postRFX, outRFX] = VBA_groupBMC(perm_1st_logBFs', optionsBMC);
    Ef = outRFX.Ef(:);
    ep = outRFX.ep(:);

    fprintf('Random-effects model comparison (RFX BMC)\n');
    for ii = 1:itt
        fprintf(['Model %d (%s): Ef = %.3f, ep = %.3f ', ...
                 '(n_wins = %d, sum F = %.2f)\n'], ...
                ii, modelNames{ii}, Ef(ii), ep(ii), win_counts(ii), ...
                F_group(ii));
    end
    fprintf(['Note: Ef = expected model frequency; ep = exceedance', ...
        ' probability.\n']);

    perm_out_name = sprintf('%s_bmc_results', net);
    save(fullfile(mfs_path, perm_out_name), ...
         'perm_1st_logBFs', 'Ef', 'ep', 'postRFX', 'outRFX', ...
         'win_counts', 'F_group', 'perm_2nd_logBFs', 'net', 'itt');

    fprintf('Saved toy permutation results: %s\n', ...
        fullfile(mfs_path, [perm_out_name, '.mat']));
end

function Fc = Fc_gaussKL(qE, qC, pE, pC)

% Fc = KL( N(qE,qC) || N(pE,pC) )  (Gaussian complexity term)
dq = spm_vec(qE) - spm_vec(pE);
P0 = spm_inv(pC);
k = numel(dq);
Fc = 0.5 * (trace(P0 * qC) + dq' * P0 * dq - k + spm_logdet(pC) - ...
    spm_logdet(qC));
Fc = full(Fc);

end
